name: Test
on:
  workflow_call:
    secrets:
      github-token:
        required: true
        description: |
          The token to use for making authenticated GitHub API requests.
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
      - id: setup-deno
        name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - id: test
        name: Test
        continue-on-error: true
        run: |
          deno test --clean --coverage=coverage
      - id: print-coverage-results
        name: Print coverage results
        if: steps.test.outcome == 'success'
        run: |
          deno coverage --exclude='\.spec\.ts$' --detailed coverage
